sudo: false
language: groovy
cache:
  directories:
  - "$HOME/.gradle/caches"
  - "$HOME/.gradle/wrapper"
jdk:
- oraclejdk7
install: "./install-dependencies.sh"
script: "./travis-build.sh"
branches:
  only:
    - master
    - /^[0-9.]+.*$/
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
before_script:
  - rm -rf target
  - rm -rf docs
env:
  global:
  - GIT_NAME="Brian Saville"
  - GIT_EMAIL="bksaville@gmail.com"
  # travis encrypt -a env.global 'GRAILS_CENTRAL_USERNAME=myusername'
  # travis encrypt -a env.global 'GRAILS_CENTRAL_PASSWORD=mypassword'
  # travis encrypt -a env.global 'BINTRAY_USER=myusername'
  # travis encrypt -a env.global 'BINTRAY_KEY=mypassword'
  # travis encrypt -a env.global 'GITHUB_TOKEN=token' # get the token from https://github.com/settings/applications
  - secure: aHPAUuip+gWj3pba1S6aqMkdVe5DQSN9hL/X0K5vY4HDrsJ3FE15CkcgFT9il02SiyIUJHY3esdnW/gaK55lzPCv0b6GRLrZfE/qSwpVzEyxyfBK15OYNzQm/jH10kJXUVbGhF0hpkLO8x9kVGJJsdKqSH5YsFYXFPEEL7xUo74=
  - secure: YMCir5j/i6T7IJd3D4QqQifyDlXComWMzCJI9W2QWvHbZ90YmRufIe+HlTtIP7HJEbJsXXR1f94dSiXTie0nbSWById27HwhnX30AcRExItn4MsgOhOeiHLR4946X8JSP6zcy+BiSAlpkxVDCHmEo6FW4onHt/G+spwcFZ1KbP8=
  - secure: dVM+jJNq6YB0o6Fw48aST6oZ7QusSoMoiUBD71/QOW679J1XIQHwaP2RYRqGY5b6A6ub6X7WaSkJ+d569BTL491S7buJxH0+OqSGrduxCxOIkc/9O9eX26WoZtnseKJy2SjclFJaomusLKtvTLrR3nz0SL2sMuAhkCqu0ksbk6o=
  - secure: ZKSGT4j+qrm/kGXIGCq4g8n5oDY7F20mevmA0e+y9/TSutNQZ4rz7f0DYp+I6kH4SZTM0RksSJNff/kFA3hE6VQqINcivU6dOIrVCFH0aWJO3nMo+7y37ZjhtfqkYpVxX5HIUmEINn80yL1aMEcFx2Ji5rc3+v3UVOWPnnlhfjY=
  - secure: JZMnGIywsEIG9s9dPQ3KQlCoqjPYxDXPKEGSAylFpSKmBXPCUnoZsAefFrgnajFJDlXMlV8VL1PSqn//KUOFuSurPym+ZTg0HfNeWs7K50yg3J5465gE9NzDLJBGDJDVa31nuEsI54QdxoJy6pUPA+l9nIJYz3dbBYe03GYpT94=
